// Obsidian 插件打包（官方样例模式）：esbuild 单文件 bundle 到 plugin 根目录 main.js
// 构建环境：PICKPEN_ENV ∈ {local, test, prod}（缺省 test），
// 配置从 plugin/config/<env>.ts 加载，经 define 注入为 process.env.PICKPEN_* 编译期常量。
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

// ---- 环境判定与配置加载（node 侧，配置文件不进产物）----
// 注意：本文件为 .mjs（纯 JS），不能用 TS 语法；config/*.ts 由 node 类型剥离（strip-only）加载，
// 故其中只使用可擦除语法（interface / import type / 类型注解），不用 as 断言
const PICKPEN_ENVS = ["local", "test", "prod"];
const env = process.env.PICKPEN_ENV ?? "test";
if (!PICKPEN_ENVS.includes(env)) {
	console.error(`错误: 未知环境 PICKPEN_ENV='${env}'（支持 ${PICKPEN_ENVS.join("/")}）`);
	process.exit(1);
}
// node ≥22.18 原生支持 TS 类型剥离，直接 import .ts 配置
const envConfig = (await import(`./config/${env}.ts`)).default;
// 支持 PICKPEN_BASE_URL 环境变量覆盖注入值（移动端联调可指向局域网内的自建后端；
// 桌面版不设置该变量，行为不变）
const baseUrl = process.env.PICKPEN_BASE_URL ?? envConfig.baseUrl;
const checkoutUrl = process.env.PICKPEN_CHECKOUT_URL ?? envConfig.checkoutUrl;
// 本地 dev 构建标识：构建脚本注入 PICKPEN_BUILD_TAG，设置面板据此显示「本地构建」，
// 与正式渠道包区分；未设置（正式发布）注入空串，产物不显示标记。
const buildTag = process.env.PICKPEN_BUILD_TAG ?? "";
if (env === "prod" && envConfig.baseUrl.includes("example.com")) {
	console.warn(`警告: prod 使用占位域名 ${envConfig.baseUrl}，上线前请修改 plugin/config/prod.ts`);
}

const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Built for env=${env}
*/`;

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/index.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
		"node:*",
	],
	// 编译期注入（define 文本替换）：代码中的 process.env.PICKPEN_* 变为字符串字面量，
	// 运行时无 process 访问；产物只含当前环境的值。约定：代码只用注入过的 PICKPEN_* 键。
	define: {
		"process.env.PICKPEN_ENV": JSON.stringify(env),
		"process.env.PICKPEN_BASE_URL": JSON.stringify(baseUrl),
		"process.env.PICKPEN_CHECKOUT_URL": JSON.stringify(checkoutUrl),
		"process.env.PICKPEN_DESKTOP_POLL_INTERVAL_MS": JSON.stringify(envConfig.desktopPollIntervalMs),
		"process.env.PICKPEN_BUILD_TAG": JSON.stringify(buildTag),
	},
	loader: {
		".svg": "text",
	},
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
